### ISSUE TITLE
Installing pdm-shell downgrades pdm

### ISSUE THREAD

**Issue by leosannlsn** [abersheeran/pdm-shell#2]
Installing `pdm-shell` downgrades my `pdm` version from 2.2.1 to 1.15.5
This causes problems with other plugins I have installed.

**Comment by abersheeran** [comment]
https://pypi.org/project/pdm-shell/

Fixed it in 1.1.0

**Comment by leosannlsn** [comment]
Wow, thanks a lot! 👍
